server:
  port: 9000
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
